Datasets Page structure
Studigrad/group-project pull request #9
Opened 2024-02-21 16:31 UTC by ArsenBuhaienko

2024-02-21 16:43 UTC, Studigrad approved these changes

2024-02-21 16:43 UTC, Studigrad commented on page-object/BasePage.ts
> +    this.expectedUrlMainPage = "https://www.kaggle.com";
Впринципі цю урлу можна в env змінну

2024-02-21 16:43 UTC, Studigrad commented on page-object/BasePage.ts
> +  expectedUrlMainPage: string;
Цікаво, може її статичною зробити ?

2024-02-21 16:44 UTC, Studigrad commented on page-object/BasePage.ts
> +    this.expectedUrlMainPage = "https://www.kaggle.com";
Зробити якось так
this.expectedUrlMainPage = process.env.BASE_URL

2024-02-22 17:38 UTC, Studigrad commented on tests/DatasetsTests/smokeTest.spec.ts
> +    await datasetsPage.openDatasetsPage;
openDatasetsPage()

2024-02-22 17:38 UTC, Studigrad commented on tests/DatasetsTests/smokeTest.spec.ts
> +    await datasetsPage.openMainPage;
openMainPage()

2024-02-25 17:32 UTC, Studigrad approved these changes
Усе виправив!

2024-02-25 17:54 UTC, holllyrash approved these changes

2024-02-26 21:43 UTC, alexredko0004 requested changes

2024-02-26 21:43 UTC, alexredko0004 commented on tests/DatasetsTests/smokeTest.spec.ts
> +    await datasetsPage.openDatasetsPage();
1) Please add some asserts here
2) There are also no download actions (based on the task of your group)

2024-02-27 05:51 UTC, alexredko0004 approved these changes

2024-02-27 15:05 UTC, merged